language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
  - "$HOME/.npm"
jobs:
  include:
  - stage: deploy-playground
    install: true
    if: branch = develop AND type = push
    script:
    - echo 'Deploying to NOW'
    - npm i -g now
    - export GIT_REV=`git rev-parse --short HEAD`
    - npm run deploy-now-playground && npm run alias-playground
env:
  global:
  - secure: v/ahKunTJk0aJE6hFMTeC7ycPiqTM4w+Q6myaCd5V5aSu0fEZZ5wB2zFQH6tTppAf1jEl0xjViaYT2mOv6TrPLZWy6G3dbzDECSyrPZGkcQoFveJewaAWz7chGe7KmWP66PSNp515D+msvZQ6kqXOpDhkfmwqGTyAxF1UAJBumqVhm6OFLuARWkaffJIHaM4XmGY8kDhYgIyyvhBIoSaa74/EHKfyK2xqmz121eyl705U8J6doxiegCTh4+TQk8lDtbdcZky4dZZEaCPrOTTc5O4KKyu/yUD10otxvf9seJE0czSuWVKXkKvNLaMslwqY2Yzkmgwy1pYGvof+GhRfWVRGKETnnboEQgBcuwinZ4k2eKNjl2gZ+wk9JBGJ3lW0JM5NB5r/9ou3El+ecbfdIl9yPmR/rkw4A51JiIb3/N3ifeQ1K3R3BL3pVUmXLHU3ikEhA3l+DP4YZniSh0C9u+WVZa1JKEhXVWwldYolWqMwR2FE8oSg0UiB0sbvdNFw2t3EPvRD0ZQBXE6qAWvC4bvTw4xMPFh0hrAJUdM/YvnNr9+b7P6KWteNOQb3oivYW8szaNgyZ/J+3wWXddWodfF5PyCvJ99Mp706MmIG78VTaty+0U6CPjXVcvspwpVUvcSDa04W3JJtLNr9vauSSvDl7SiFtnp7KlEk7dYiUg=
  - secure: 3GRN+gQfwBl7kYJ5euuiv9BWKFB2Hn8Lmwk8ebdyS+2Bqlzy2a/83uMx9Ru7qdRywXIsLEUeHAApiQ8ca4nOxneoZd19SSlOTDNze6XnjE6Vr618knl9PdBvQGWbia7ODNQF2uWRU4dEOatbebJ3Z/ZVXrfyD6dQWOpUD7Ho/6CwwjDkQoKpcueybsS6ujyXe+yzA5iM2zNMuqPD0aYsVKzqyrGxD5pz8PGxpNgPVFIv2EA3VvrcThrf7DNzghcMnrFeSi9/nU1cMf0EevF+pxVcR8rX9Aik97QYn9hgZLMbHPplEu+MEQHFuLM22rMh6cqkNOZGKGgnj7Dv1fqc56FQftVt2Gp79QhICQBkWc3Sflh7o+lvmjCtBmhkfGrDv5D78k8s53cbUX3CHKONbHFIelnJB+ZzZ/OyqVCb7YYXesUj5GRcXZQIMRZyMq6K0hcbudB5GENrV9DdLcYJVB+K5g5AhqxxStHAEfXhPxx2sIr6EBDaSndj84nzhFxYWnfQFdkshGtsJp5JFY7IuOH3o9vdFE0kqbTu1yOtlZHS0DPPZeupNLcBp/OnZm8B0Inbp+p39vIo8CvyvTYIyFh1yTCq1nFHHW/NDNwT+8oX2mH3PGXPzFjGR9x50e+5vd5VLVCY6aJvep+L2+QERJ7goGF6hyf4VpRWBm/Yhr0=
